<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            [
                'name'        => 'Création Site Web Vitrine - 5 Pages',
                'description' => 'Pack Silver : Site WordPress 5 pages avec CMS, intégration charte graphique, design responsive, SEO friendly, certificat SSL. Garantie 10 ans.',
                'base_price'  => 5600,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/vitrine5/600/400',
            ],
            [
                'name'        => 'Création Site web Vitrine - 9 Pages',
                'description' => 'Pack Gold : Site WordPress 9 pages clé en main avec CMS, intégration complète, design professionnel, animations, SEO friendly. Garantie 10 ans.',
                'base_price'  => 6800,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/vitrine9/600/400',
            ],
            [
                'name'        => 'Création Site Web OnePage',
                'description' => 'Site WordPress une page avec CMS, charte graphique, design responsive, formulaire de contact, SEO friendly et certificat SSL. Garantie 10 ans.',
                'base_price'  => 290,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/onepage/600/400',
            ],
            [
                'name'        => 'Création Site web Ecommerce',
                'description' => 'Boutique WordPress clé en main avec 10 produits inclus, système de gestion commandes/stock, paiement, pages catégories, SEO friendly. Garantie 10 ans.',
                'base_price'  => 7900,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/ecommerce/600/400',
            ],
            [
                'name'        => 'Création Site web Ecommerce Shopify',
                'description' => 'Boutique Shopify jusqu\'à 10 produits avec design personnalisé, système de gestion intégré, pages catégories, paiement, responsive et SEO friendly.',
                'base_price'  => 6500,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/shopify/600/400',
            ],
            [
                'name'        => 'Développement d\'une Application WEB',
                'description' => 'Application web complète avec gestion des ventes, achats, comptabilité, stocks, RH. Intégration systèmes existants, formation et support 12 mois inclus.',
                'base_price'  => 16000,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/webapp/600/400',
            ],
            [
                'name'        => 'Serveur d\'hébergement WEB - Full Pack',
                'description' => 'Hébergement 100 Dh/mois : domaine gratuit, SSL, 80GB espace, emails professionnels, LiteSpeed, sauvegarde 24/7, sécurité 24h.',
                'base_price'  => 1200,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/hosting/600/400',
            ],
            [
                'name'        => 'Maintenance et Sécurité web Annuelle',
                'description' => 'Mises à jour WordPress/plugins, firewall, scan mensuel, reCAPTCHA, sauvegarde site, réactivation SSL, protection contre attaques.',
                'base_price'  => 6000,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/maintenance/600/400',
            ],
            [
                'name'        => 'Récurrence Annuel des Sites web',
                'description' => 'Mises à jour plugins, nettoyage serveur, modifications contenu, changement données, MAJ mots clés SEO, sauvegarde 24/7, sécurité.',
                'base_price'  => 1800,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/recurrence/600/400',
            ],
            [
                'name'        => 'Référencement Naturel SEO - Phase d\'indexation',
                'description' => 'Optimisation complète SEO : correction HTML/CSS, mots clés, méta-descriptions, backlinks internes, vitesse, CDN, sitemap, indexation Google rapide, Analytics.',
                'base_price'  => 4000,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/seoindex/600/400',
            ],
            [
                'name'        => 'Référencement Naturel SEO - Suivi Mensuel',
                'description' => 'Rédaction articles optimisés, MAJ mots-clés, correction erreurs GSC, contrôle erreurs 404, création backlinks fiables, rapport Google Analytics.',
                'base_price'  => 2000,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/seomonthly/600/400',
            ],
            [
                'name'        => 'Intégration Multilingue sur Site',
                'description' => 'Installation extension multilingue, traduction contenus (pages fixes, blog), configuration balises méta et URLs, tests et validation.',
                'base_price'  => 2500,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/multilang/600/400',
            ],
            [
                'name'        => 'Ads Management - Installation Infrastructure',
                'description' => 'Configuration Meta Business Manager, Facebook/Instagram/WhatsApp, installation Pixel, Google Ads, Tag Manager, Analytics pour mesurer conversions.',
                'base_price'  => 1800,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/adsinfra/600/400',
            ],
            [
                'name'        => 'Ads Management - Gestion des Campagnes Publicitaires',
                'description' => 'Création campagnes selon objectifs, ciblage audience (âge, sexe, intérêts, localisation), conception ADSETS, suivi quotidien, optimisation performances.',
                'base_price'  => 2000,
                'tax_rate'    => 0.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/adscampaign/600/400',
            ],
            [
                'name'        => 'Social Media Management - Mensuel',
                'description' => 'Configuration Meta Business, analyse concurrents, calendrier mensuel, 3 posts + 2 stories/semaine, hashtags, réponse commentaires/DM, rapports hebdomadaires.',
                'base_price'  => 3500,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/smm/600/400',
            ],
            [
                'name'        => 'Conception LOGO',
                'description' => 'Logo complexe (2 propositions), PNG transparent, résolution 300 DPi print/web, CMYK/RGB, 3 couleurs, retouches illimitées, modélisation, fichiers sources.',
                'base_price'  => 990,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/logo/600/400',
            ],
            [
                'name'        => 'Création d\'une nouvelle BRAND - Full Pack',
                'description' => 'Analyse concurrents, stratégie branding complète, création logo (2 propositions), charte graphique globale avec palettes couleurs, typographie, icons.',
                'base_price'  => 7000,
                'tax_rate'    => 0.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/fullbrand/600/400',
            ],
            [
                'name'        => 'Création document Charte Graphique',
                'description' => 'Document de référence complet pour identité visuelle. Définition couleurs, typographies, règles utilisation logo et éléments graphiques déclinables.',
                'base_price'  => 5000,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/charte/600/400',
            ],
            [
                'name'        => 'Conception Graphique - Flyers',
                'description' => 'Conception 1 proposition, PNG transparent, résolution 300 DPi optimisée impression/web, CMYK/RGB, retouches illimitées, fichiers sources.',
                'base_price'  => 900,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/flyers/600/400',
            ],
            [
                'name'        => 'Conception Pancarte / Flyers / Affiche',
                'description' => 'Conception 1 proposition selon dimensions, PNG transparent, 300 DPi, CMYK/RGB, retouches illimitées, fichiers sources (.Ai + .PSD + JPEG/PNG/PDF).',
                'base_price'  => 1000,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/pancarte/600/400',
            ],
            [
                'name'        => 'Conception Packaging Produit',
                'description' => 'Design d\'emballage unique et attrayant pour chaque produit. Dimensions selon cahier des charges, ressources premium exclusives, retouches illimitées.',
                'base_price'  => 1500,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/packaging/600/400',
            ],
            [
                'name'        => 'Montage Vidéo & Vidéo Ads',
                'description' => 'Vidéo 1min avec rythme dynamique, titres/textes, animations, transitions, vidéos d\'illustration, musique, mixage audio, bruitages, retouches illimitées.',
                'base_price'  => 1200,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/videoads/600/400',
            ],
            [
                'name'        => 'Filming & vidéographie du local ou Service',
                'description' => 'Vidéo durée 30-40s avec montage, effets spéciaux, animations, musique, son, modifications inclus.',
                'base_price'  => 2000,
                'tax_rate'    => 0.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/filming/600/400',
            ],
            [
                'name'        => 'Impression Carte Visite',
                'description' => 'Cartes visite standard recto verso, papier couché 350g, pelliculage matt, coins normaux.',
                'base_price'  => 0.05,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/cartevisite/600/400',
            ],
            [
                'name'        => 'Impression Flyers A5',
                'description' => 'Flyers A5 (21x14.8cm), papier couché 135g mat/brillant, impression quadri recto ou recto verso, options pelliculage et finition luxe disponibles.',
                'base_price'  => 0.80,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/flyersa5/600/400',
            ],
            [
                'name'        => 'Impressions Papier en tete Standard',
                'description' => 'Quantité min 100. Format 21x29.7cm, papier non couché 90gr Target, impression quadri recto seul.',
                'base_price'  => 230,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/entete/600/400',
            ],
            [
                'name'        => 'Pancarte externe Professionnel - Plexiglas',
                'description' => 'Format 21x29.7cm, plexiglas blanc 3mm, impression quadri recto.',
                'base_price'  => 600,
                'tax_rate'    => 0.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/plexiglas/600/400',
            ],
            [
                'name'        => 'Pancarte Interne / Externe - Vinyle OneWay',
                'description' => 'Prix par m², quadri HD standard.',
                'base_price'  => 200,
                'tax_rate'    => 0.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/vinyle/600/400',
            ],
            [
                'name'        => 'Service EXTRA',
                'description' => 'Correction bugs, développement système réservation/ecommerce/compte, formulaire contact avec récupération emails automatique (Google Sheets), etc.',
                'base_price'  => 1200,
                'tax_rate'    => 20.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/extra/600/400',
            ],
            [
                'name'        => 'SAV',
                'description' => 'Prestation mensuelle : suivi et réponse aux demandes clients, gestion des commandes sur Shopify.',
                'base_price'  => 5000,
                'tax_rate'    => 0.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/sav/600/400',
            ],
            [
                'name'        => 'Copie / Clone Site web existant',
                'description' => 'Changement liens, redirections, infos personnelles (nom, numéro, adresse), images, styling, sauvegarde.',
                'base_price'  => 2000,
                'tax_rate'    => 0.00,
                'status'      => 'active',
                'image'       => 'https://picsum.photos/seed/clone/600/400',
            ],
        ];

        foreach ($services as $service) {
            DB::table('services')->insert([
                'name'        => $service['name'],
                'description' => $service['description'],
                'base_price'  => $service['base_price'],
                'tax_rate'    => $service['tax_rate'],
                'status'      => $service['status'],
                'image'       => $service['image'],
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ]);
        }
    }
}